# Generated by Django 4.2.16 on 2024-12-02 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_profile_github_repos_profile_last_github_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="removal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="answer",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="removal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
