# Generated by Django 5.1.4 on 2025-04-17 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projectdiscussion_course_question_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubShowcasedRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=100)),
                ("owner_avatar_url", models.URLField(blank=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("readme", models.TextField(blank=True)),
                ("stargazers_count", models.IntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("votes", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GitHubRepoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.githubshowcasedrepo",
                    ),
                ),
            ],
        ),
    ]
