# Generated by Django 5.1.4 on 2025-04-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_githubrepovote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="github_repo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.githubshowcasedrepo",
            ),
        ),
        migrations.DeleteModel(name="GitHubRepoVote",),
    ]
